// Generated by Apple Swift version 3.1 (swiftlang-802.0.48 clang-802.0.38)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if defined(__has_attribute) && __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import CoreGraphics;
@import ObjectiveC;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class UIColor;
@class NSCoder;

SWIFT_CLASS("_TtC21HarishFrameworkSwift36Button")
@interface Button : UIButton
@property (nonatomic) BOOL isBorder;
@property (nonatomic) NSInteger border;
@property (nonatomic) NSInteger radious;
@property (nonatomic, strong) UIColor * _Nullable borderColor;
@property (nonatomic) BOOL isShadow;
@property (nonatomic, strong) UIColor * _Nullable shadow_Color;
@property (nonatomic) CGFloat ls_Opacity;
@property (nonatomic) NSInteger ls_Radius;
@property (nonatomic) CGFloat lsOff_Width;
@property (nonatomic) CGFloat lsOff_Height;
@property (nonatomic) BOOL isStrokeColor;
- (void)drawRect:(CGRect)rect;
- (void)layoutSubviews;
- (void)border1:(UIColor * _Nullable)color :(CGFloat)cornerRadius :(CGFloat)borderWidth;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol FloatRatingViewDelegate;
@class UIImage;
@class UITouch;
@class UIEvent;

/// A simple rating view that can set whole, half or floating point ratings.
SWIFT_CLASS("_TtC21HarishFrameworkSwift315FloatRatingView")
@interface FloatRatingView : UIView
@property (nonatomic, weak) id <FloatRatingViewDelegate> _Nullable delegate;
/// Sets the empty image (e.g. a star outline)
@property (nonatomic, strong) UIImage * _Nullable emptyImage;
/// Sets the full image that is overlayed on top of the empty image.
/// Should be same size and shape as the empty image.
@property (nonatomic, strong) UIImage * _Nullable fullImage;
/// Minimum rating.
@property (nonatomic) NSInteger minRating;
/// Max rating value.
@property (nonatomic) NSInteger maxRating;
/// Minimum image size.
@property (nonatomic) CGSize minImageSize;
/// Set the current rating.
@property (nonatomic) float rating;
/// Sets whether or not the rating view can be changed by panning.
@property (nonatomic) BOOL editable;
/// Ratings change by 0.5. Takes priority over floatRatings property.
@property (nonatomic) BOOL halfRatings;
/// Ratings change by floating point values.
@property (nonatomic) BOOL floatRatings;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesMoved:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
@end


SWIFT_PROTOCOL("_TtP21HarishFrameworkSwift323FloatRatingViewDelegate_")
@protocol FloatRatingViewDelegate
/// Returns the rating value when touch events end
- (void)floatRatingView:(FloatRatingView * _Nonnull)ratingView didUpdate:(float)rating;
@optional
/// Returns the rating value as the user pans
- (void)floatRatingView:(FloatRatingView * _Nonnull)ratingView isUpdating:(float)rating;
@end

@class NSMutableDictionary;
@class NSDictionary;
@class NSMutableArray;
@class UIAlertAction;

SWIFT_CLASS("_TtC21HarishFrameworkSwift34Http")
@interface Http : NSObject
+ (Http * _Nonnull)instance SWIFT_WARN_UNUSED_RESULT;
- (void)json:(NSString * _Nullable)api :(NSMutableDictionary * _Nullable)params :(NSString * _Nullable)method ai:(BOOL)ai popup:(BOOL)popup prnt:(BOOL)prnt :(NSDictionary * _Nullable)header :(NSMutableArray * _Nullable)images sync:(BOOL)sync completionHandler:(void (^ _Nonnull)(NSDictionary * _Nullable, NSMutableDictionary * _Nullable, NSString * _Nonnull))completionHandler;
- (void)jsonThread:(NSMutableDictionary * _Nonnull)md;
- (NSString * _Nonnull)generateBoundaryString SWIFT_WARN_UNUSED_RESULT;
+ (void)startActivityIndicator;
+ (void)stopActivityIndicator;
- (void)startActivityIndicator;
- (void)stopActivityIndicator;
+ (void)startActivityIndicatorThread;
+ (void)stopActivityIndicatorThread;
- (NSDictionary<NSString *, id> * _Nullable)convertStringToDictionaryWithText:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
- (void)attributedString;
+ (void)alert:(NSString * _Nullable)ttl :(NSString * _Nullable)msg;
- (void)alert:(NSString * _Nullable)ttl :(NSString * _Nullable)msg;
+ (void)alert:(NSString * _Nullable)ttl :(NSString * _Nullable)msg :(NSArray * _Nonnull)btns;
+ (void)alertFailed:(NSDictionary * _Nullable)json :(NSString * _Nonnull)key;
+ (UIAlertAction * _Nonnull)alertAction:(NSArray * _Nonnull)btns :(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)currTime SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIActivityIndicatorView;
@class UITapGestureRecognizer;
@class UIPinchGestureRecognizer;

SWIFT_CLASS("_TtC21HarishFrameworkSwift39ImageView")
@interface ImageView : UIImageView
@property (nonatomic) BOOL isBorder;
@property (nonatomic) NSInteger border;
@property (nonatomic) NSInteger radious;
@property (nonatomic, strong) UIColor * _Nullable borderColor;
@property (nonatomic) BOOL isShadow;
@property (nonatomic, strong) UIColor * _Nullable shadow_Color;
@property (nonatomic) CGFloat ls_Opacity;
@property (nonatomic) NSInteger ls_Radius;
@property (nonatomic) CGFloat lsOff_Width;
@property (nonatomic) CGFloat lsOff_Height;
@property (nonatomic) BOOL isStrokeColor;
- (void)layoutSubviews;
- (void)border1:(UIColor * _Nullable)color :(CGFloat)cornerRadius :(CGFloat)borderWidth;
@property (nonatomic) BOOL willZoom;
@property (nonatomic, strong) UIColor * _Nonnull background_color;
- (void)drawRect:(CGRect)rect;
- (void)setImage:(UIView * _Nullable)superView :(NSString * _Nullable)urlImage :(NSString * _Nullable)dImage :(BOOL)boolScal :(UIActivityIndicatorView * _Nullable)ai;
- (void)createZoomView:(UIView * _Nullable)superView;
- (void)setUIImage;
- (void)addClickButton:(CGRect)rect;
- (void)imageTapped:(UITapGestureRecognizer * _Nonnull)tapGestureRecognizer;
- (void)openZoomView:(id _Nonnull)sender;
- (IBAction)actionRemoveZoomContainer:(id _Nonnull)sender;
- (void)addPichZoom;
- (void)twoFingerPinch:(UIPinchGestureRecognizer * _Nonnull)recognizer;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC21HarishFrameworkSwift35Label")
@interface Label : UILabel
@property (nonatomic) BOOL isBorder;
@property (nonatomic) NSInteger border;
@property (nonatomic) NSInteger radious;
@property (nonatomic, strong) UIColor * _Nullable borderColor;
@property (nonatomic) BOOL isShadow;
@property (nonatomic, strong) UIColor * _Nullable shadow_Color;
@property (nonatomic) CGFloat ls_Opacity;
@property (nonatomic) NSInteger ls_Radius;
@property (nonatomic) CGFloat lsOff_Width;
@property (nonatomic) CGFloat lsOff_Height;
@property (nonatomic) BOOL isStrokeColor;
- (void)drawRect:(CGRect)rect;
- (void)layoutSubviews;
- (void)border1:(UIColor * _Nullable)color :(CGFloat)cornerRadius :(CGFloat)borderWidth;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface NSArray (SWIFT_EXTENSION(HarishFrameworkSwift3))
- (NSString * _Nonnull)convertToString SWIFT_WARN_UNUSED_RESULT;
- (NSMutableArray * _Nullable)getMutable:(NSMutableArray * _Nullable)ma SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)convertToString:(BOOL)caller SWIFT_WARN_UNUSED_RESULT;
@end


@interface NSDictionary (SWIFT_EXTENSION(HarishFrameworkSwift3))
- (NSString * _Nonnull)convertToString SWIFT_WARN_UNUSED_RESULT;
- (NSMutableDictionary * _Nullable)getMutable:(NSMutableDictionary * _Nullable)md SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)convertToString:(BOOL)caller SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC21HarishFrameworkSwift34Test")
@interface Test : NSObject
- (void)test;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC21HarishFrameworkSwift39TextField")
@interface TextField : UITextField
@property (nonatomic) BOOL isBorder;
@property (nonatomic) NSInteger border;
@property (nonatomic) NSInteger radious;
@property (nonatomic, strong) UIColor * _Nullable borderColor;
@property (nonatomic) BOOL isShadow;
@property (nonatomic, strong) UIColor * _Nullable shadow_Color;
@property (nonatomic) CGFloat ls_Opacity;
@property (nonatomic) NSInteger ls_Radius;
@property (nonatomic) CGFloat lsOff_Width;
@property (nonatomic) CGFloat lsOff_Height;
@property (nonatomic) BOOL isStrokeColor;
@property (nonatomic) NSInteger padding;
- (void)drawRect:(CGRect)rect;
- (void)layoutSubviews;
- (void)padding:(NSInteger)pad;
- (void)border1:(UIColor * _Nullable)color :(CGFloat)cornerRadius :(CGFloat)borderWidth;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSTextContainer;

SWIFT_CLASS("_TtC21HarishFrameworkSwift38TextView")
@interface TextView : UITextView
@property (nonatomic) BOOL isBorder;
@property (nonatomic) NSInteger border;
@property (nonatomic) NSInteger radious;
@property (nonatomic, strong) UIColor * _Nullable borderColor;
@property (nonatomic) BOOL isShadow;
@property (nonatomic, strong) UIColor * _Nullable shadow_Color;
@property (nonatomic) CGFloat ls_Opacity;
@property (nonatomic) NSInteger ls_Radius;
@property (nonatomic) CGFloat lsOff_Width;
@property (nonatomic) CGFloat lsOff_Height;
@property (nonatomic) BOOL isStrokeColor;
- (void)drawRect:(CGRect)rect;
- (void)layoutSubviews;
- (void)border1:(UIColor * _Nullable)color :(CGFloat)cornerRadius :(CGFloat)borderWidth;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=7.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC21HarishFrameworkSwift35Toast")
@interface Toast : UIView
- (void)show:(NSString * _Nonnull)msg;
+ (void)toast:(NSString * _Nonnull)msg;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIColor (SWIFT_EXTENSION(HarishFrameworkSwift3))
+ (UIColor * _Nonnull)hexColorWithRgbValue:(uint32_t)rgbValue alpha:(double)alpha SWIFT_WARN_UNUSED_RESULT;
@end


@interface UIDevice (SWIFT_EXTENSION(HarishFrameworkSwift3))
@property (nonatomic, readonly, copy) NSString * _Nonnull modelName;
- (void)deviceInfo:(NSMutableDictionary * _Nullable)md;
@end


@interface UIImage (SWIFT_EXTENSION(HarishFrameworkSwift3))
- (UIImage * _Nonnull)resize:(CGFloat)wth SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)base64:(CGFloat)quality SWIFT_WARN_UNUSED_RESULT;
@end


@interface UIImageView (SWIFT_EXTENSION(HarishFrameworkSwift3))
- (void)saveImageDocumentDirectory;
- (NSString * _Nonnull)getDirectoryPath SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nullable)getImage SWIFT_WARN_UNUSED_RESULT;
- (void)createDirectory;
- (void)deleteDirectory;
- (void)deleteFileForUrl:(NSString * _Nullable)url;
- (void)savedUIImageForUrl:(NSString * _Nonnull)url block:(void (^ _Nonnull)(UIImage * _Nullable))block;
- (void)savedUIImage:(NSString * _Nullable)name block:(void (^ _Nonnull)(UIImage * _Nullable))block;
- (void)saveUIImage:(NSString * _Nullable)name :(UIImage * _Nullable)img;
- (void)saveUIImageForUrl:(NSString * _Nullable)url :(UIImage * _Nullable)img;
- (void)displayImage:(NSDictionary * _Nonnull)dict;
- (void)downloadUIImage:(NSString * _Nullable)url block:(void (^ _Nonnull)(UIImage * _Nullable))block;
- (void)downloadUIImageThread:(NSMutableDictionary * _Nonnull)md;
- (void)uiimage:(NSString * _Nullable)url :(NSString * _Nullable)dImage :(BOOL)boolScal :(UIActivityIndicatorView * _Nullable)ai :(UIView * _Nullable)superView;
- (void)getNSetUIImagee:(NSDictionary * _Nonnull)dict;
@end


@interface UITextField (SWIFT_EXTENSION(HarishFrameworkSwift3))
@end


@interface UIView (SWIFT_EXTENSION(HarishFrameworkSwift3))
- (void)border:(UIColor * _Nullable)color :(CGFloat)cornerRadius :(CGFloat)borderWidth;
- (void)shadowSubViews;
- (void)shadow;
@end

@class NSData;

SWIFT_CLASS("_TtC21HarishFrameworkSwift38UserInfo")
@interface UserInfo : NSObject <NSCoding>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSString * _Nonnull)date :(NSString * _Nonnull)email :(NSString * _Nonnull)first_name :(NSString * _Nonnull)id :(NSString * _Nonnull)image :(NSString * _Nonnull)last_name :(NSString * _Nonnull)password :(NSString * _Nonnull)status :(NSString * _Nonnull)time :(NSString * _Nonnull)allowed_time :(NSString * _Nonnull)amout :(NSString * _Nonnull)category_id :(NSString * _Nonnull)category_name :(NSString * _Nonnull)event_date :(NSString * _Nonnull)event_duration :(NSString * _Nonnull)event_status :(NSString * _Nonnull)name :(NSString * _Nonnull)start_time :(NSString * _Nonnull)paypal_id referral_code:(NSString * _Nonnull)referral_code OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
+ (NSData * _Nonnull)archivePeople:(UserInfo * _Nonnull)people SWIFT_WARN_UNUSED_RESULT;
+ (UserInfo * _Nonnull)retrievePeople:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
+ (void)save:(UserInfo * _Nonnull)ob;
- (void)save;
+ (void)logout;
+ (id _Nullable)user1 SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)user SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC21HarishFrameworkSwift35Valid")
@interface Valid : NSObject
+ (BOOL)email:(NSString * _Nonnull)testStr SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)url:(NSString * _Nonnull)testStr SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)fiscale:(NSString * _Nonnull)testStr SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)password:(NSString * _Nonnull)testStr SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)nameWithStrTest:(NSString * _Nonnull)strTest SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC21HarishFrameworkSwift34View")
@interface View : UIView
@property (nonatomic) BOOL isBorder;
@property (nonatomic) NSInteger border;
@property (nonatomic) NSInteger radious;
@property (nonatomic, strong) UIColor * _Nullable borderColor;
@property (nonatomic) BOOL isShadow;
@property (nonatomic, strong) UIColor * _Nullable shadow_Color;
@property (nonatomic) CGFloat ls_Opacity;
@property (nonatomic) NSInteger ls_Radius;
@property (nonatomic) CGFloat lsOff_Width;
@property (nonatomic) CGFloat lsOff_Height;
@property (nonatomic) BOOL isStrokeColor;
- (void)drawRect:(CGRect)rect;
- (void)layoutSubviews;
- (void)layoutSubviews11;
- (void)border1:(UIColor * _Nullable)color :(CGFloat)cornerRadius :(CGFloat)borderWidth;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
